networks:
  agent-net:
    external: true
    name: ${AGENT_NET_NAME}

services:
  agent:
    build: ./agents
    image: sicc-agent:latest
    container_name: ${AGENT_NAME}
    env_file:
      - .env
      - env/.env.agent
    environment:
      - IOT_SERVER_URL=http://iot-server:7000
      - AGENT_NAME=${AGENT_NAME}
    networks:
      - agent-net
    restart: unless-stopped
    labels:
      - ${AGENT_LABEL}
