services:

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - BACKEND_URL=${BACKEND_URL}
    depends_on:
      - backend
    networks:
      - public

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend:/app
    env_file: .env
    environment:
      - ENV=development
    depends_on:
      db:
        condition: service_healthy
      iot-server:
        condition: service_started
    networks:
      - public
      - internal

  iot-server:
    build: ./ServerIoT
    ports:
      - "${IOT_SERVER_PORT}:7000"
    volumes:
      - ./ServerIoT:/app
    env_file: .env
    environment:
      - ENV=development
      - BACKEND_URL=${BACKEND_URL}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
      - agent-net

  agent-1:
    build: ./agents
    env_file: .env
    environment:
      - AGENT_ID=1
      - ENV=development
    networks:
      - agent-net

  agent-2:
    build: ./agents
    env_file: .env
    environment:
      - AGENT_ID=2
      - ENV=development
    networks:
      - agent-net

  db:
      build: ./db
      volumes:
        - postgres_data:/var/lib/postgresql/data
      env_file: .env
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
        interval: 5s
        timeout: 5s
        retries: 5
      networks:
        - internal

networks:
  public:       # frontend <-> backend
  internal:     # backend <-> iot-server <-> db
  agent-net:    # iot-server <-> agents

volumes:
  postgres_data: