services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
      - env/.env.frontend
    depends_on:
      - backend
    networks:
      - public

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
      - env/.env.backend
    depends_on:
      db:
        condition: service_healthy
      iot-server:
        condition: service_started
    networks:
      - public
      - internal

  iot-server:
    build: ./server-iot
    ports:
      - "${IOT_SERVER_PORT}:7000"
    volumes:
      - ./server-iot:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
      - agent-net

  db:
    build: ./db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

networks:
  public:
  internal:
  agent-net:
    name: ${AGENT_NET_NAME}

volumes:
  postgres_data: