#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE ROLE ${DB_BACKEND_USER} LOGIN PASSWORD '${DB_BACKEND_PASSWORD}';
CREATE ROLE ${DB_IOT_USER}     LOGIN PASSWORD '${DB_IOT_PASSWORD}';
EOSQL